// const categories = {
//   bank: '🏦 Bank',
//   beauty: '💅 Beauty',
//   business: '💵 Business',
//   car: '🚗 Car',
//   charity: '🤝 Charity',
//   clothing: '🧥 Clothing',
//   food: '🍽 Food',
//   restaurants: '🍸 Restaurants',
//   education: '🎓 Education',
//   entertaiment: '🎥 Entertaiment',
//   gifts: '🎁 Gifts',
//   hardware: '🖥 Hardware',
//   healthcare: '💊 Healthcare',
//   home: '🏠 Home',
//   kids: '👨‍👩‍👧‍👦 Kids',
//   phone: '📱 Phone',
//   other: '👀 Other',
//   pets: '🐾 Pets',
//   state: '🏢 State',
//   transport: '🚌 Transport',
//   travel: '⛺ Travel',
// };

const categories = [
  '🏦 Bank',
  '💅 Beauty',
  '💵 Business',
  '🚗 Car',
  '🤝 Charity',
  '🧥 Clothing',
  '🍽 Food',
  '🍸 Restaurants',
  '🎓 Education',
  '🎥 Entertaiment',
  '🎁 Gifts',
  '🖥 Hardware',
  '💊 Healthcare',
  '🏠 Home',
  '👨‍👩‍👧‍👦 Kids',
  '📱 Phone',
  '👀 Other',
  '🐾 Pets',
  '🏢 State',
  '🚌 Transport',
  '⛺ Travel',
];

export default categories;
